### ISSUE TITLE
Type defs?

### ISSUE THREAD

**Issue by KWolfe81** [mjcross/esp32_onewire#1]
Where do you define uint used in ow_send and ow_send_bit?

**Comment by mjcross** [comment]
It's in `xtensa-esp-elf/sys-include/sys/types.h`, under `~/.espressif/tools/`:

```
#if __MISC_VISIBLE
typedef	unsigned short	ushort;		/* System V compatibility */
typedef	unsigned int	uint;		/* System V compatibility */
typedef	unsigned long	ulong;		/* System V compatibility */
#endif
```

If your build environment isn't pulling in that system header automatically then you might try adding `#include <types.h>` explicitly to `include/onewire.h`. If that doesn't work you should be able to use `unsigned int` or `uint8_t` instead.

** UPDATE: commit [383ebe2](https://github.com/mjcross/esp32_onewire/commit/383ebe2be02ed99d3efa13c36f8b9c77a1622651) replaces occurrences of `uint` with `unsigned int` **
